(defpackage #:mysql-login-path-parser.tests
  (:use #:cl #:fiveam #:mysql-login-path-parser)
  (:export #:run-mysql-tests))

(in-package #:mysql-login-path-parser.tests)

(def-suite mysql-login-path-parser-tests
  :description "Test suite for MySQL login path parser")

(in-suite mysql-login-path-parser-tests)

;;; Fixtures in tests/fixtures/*.cnf are generated by tests/fixtures/make-fixtures.sh
;;; using MySQL's own mysql_config_editor. See that script for their contents.

(defun fixture (name)
  "Absolute pathname of the .cnf fixture named NAME."
  (asdf:system-relative-pathname
   :mysql-login-path-parser (format nil "tests/fixtures/~A.cnf" name)))

(defun field (alist key)
  (cdr (assoc key alist :test #'string=)))

;;; --- Unit tests ---------------------------------------------------------

(test test-constants
  "Test that constants are defined correctly"
  (is (= mysql-login-path-parser::+mysql-header-size+ 4))
  (is (= mysql-login-path-parser::+mysql-key-size+ 20))
  (is (= mysql-login-path-parser::+mysql-total-header-size+ 24)))

(test test-read-uint32-le
  "Test little-endian integer reading"
  (let ((data #(#x12 #x34 #x56 #x78)))
    (is (= (mysql-login-path-parser::read-uint32-le data 0) #x78563412))))

(test test-read-null-terminated-string
  "Test null-terminated string reading"
  (let ((data (concatenate 'vector
                           (map 'vector #'char-code "hello")
                           #(0)
                           (map 'vector #'char-code "world"))))
    (multiple-value-bind (str next-pos)
        (mysql-login-path-parser::read-null-terminated-string data 0)
      (is (string= str "hello"))
      (is (= next-pos 6)))))

(test test-fold-aes-key
  "The 20-byte stored key is XOR-folded into a 16-byte AES-128 key"
  (let ((folded (mysql-login-path-parser::fold-aes-key
                 (coerce (loop for i below 20 collect i)
                         '(vector (unsigned-byte 8))))))
    (is (= 16 (length folded)))
    ;; bytes 16..19 fold back onto positions 0..3: i XOR (i+16) = 16
    (is (equalp #(16 16 16 16 4 5 6 7 8 9 10 11 12 13 14 15) folded))))

;;; --- Fixture-based parsing tests ---------------------------------------

(test test-parse-basic-fixture
  "Parse a file with multiple login paths and assorted fields"
  (let ((paths (parse-mylogin-cnf (fixture "basic"))))
    (is (equal '("local" "staging") (mapcar #'car paths)))
    (let ((local (field paths "local")))
      (is (string= "root" (field local "user")))
      (is (string= "secret" (field local "password")))
      (is (string= "localhost" (field local "host"))))
    (let ((staging (field paths "staging")))
      (is (string= "deploy" (field staging "user")))
      (is (string= "st@ging-pw" (field staging "password")))
      (is (string= "db.staging.example.com" (field staging "host")))
      (is (string= "3307" (field staging "port"))))))

(test test-parse-single-fixture
  "Parse a file with a single login path and one field"
  (let ((paths (parse-mylogin-cnf (fixture "single"))))
    (is (= 1 (length paths)))
    (is (string= "client" (car (first paths))))
    (is (string= "admin" (field (cdr (first paths)) "user")))))

(test test-parse-special-fixture
  "Values containing '=', '#', quotes and spaces survive parsing intact"
  (let ((weird (field (parse-mylogin-cnf (fixture "special")) "weird")))
    (is (string= "the user" (field weird "user")))
    ;; mysql_config_editor stores the embedded quote escaped as \" ; the
    ;; '=' and '#' inside the value must survive intact.
    (is (string= "a=b=c#\"x" (field weird "password")))))

(test test-parse-empty-fixture
  "A header-only file (no login paths) parses to an empty list"
  (is (null (parse-mylogin-cnf (fixture "empty")))))

(test test-list-login-paths-fixture
  "list-login-paths returns the path names in file order"
  (is (equal '("local" "staging") (list-login-paths (fixture "basic"))))
  (is (equal '("client") (list-login-paths (fixture "single"))))
  (is (null (list-login-paths (fixture "empty")))))

(test test-get-credentials-fixture
  "get-login-path-credentials returns the right section, or nil if missing"
  (let ((creds (get-login-path-credentials "staging" (fixture "basic"))))
    (is (string= "deploy" (field creds "user")))
    (is (string= "st@ging-pw" (field creds "password"))))
  (is (null (get-login-path-credentials "does-not-exist" (fixture "basic")))))

(test test-read-aes-key-from-file
  "The folded AES key extracted from a real file is 16 bytes"
  (is (= 16 (length (read-aes-key-from-file (fixture "basic"))))))

;;; --- Error / edge-case handling ----------------------------------------

(test test-list-login-paths-nonexistent
  "Test listing paths from nonexistent file"
  (let ((paths (list-login-paths "/nonexistent/file")))
    (is (null paths))))

(test test-get-credentials-nonexistent
  "Test getting credentials from nonexistent file"
  (let ((creds (get-login-path-credentials "test" "/nonexistent/file")))
    (is (null creds))))

(test test-parse-nonexistent-signals
  "Parsing a missing file signals our parse error"
  (signals mysql-login-path-parse-error
    (parse-mylogin-cnf "/nonexistent/file")))

(test test-conditions
  "Test that custom conditions are defined"
  (signals mysql-login-path-error
    (error 'mysql-login-path-error :message "test"))
  (signals mysql-login-path-parse-error
    (error 'mysql-login-path-parse-error :message "test"))
  (signals mysql-login-path-decrypt-error
    (error 'mysql-login-path-decrypt-error :message "test")))

(defun run-mysql-tests ()
  "Run all tests and return T if all pass, NIL otherwise"
  (format t "Running MySQL login path parser tests...~%")
  (run! 'mysql-login-path-parser-tests))
